server:
  port: 8092

spring:
  main:
    allow-bean-definition-overriding: true
  threads:
    virtual:
      enabled: true
  application:
    name: ${application.name}
  webflux:
    problemdetails:
      enabled: true
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: ${mongo.db}
